[package]
name = "wawawa"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = { version = "1.19.0", features = ["derive"] }
env_logger = "0.11.5"
image = "0.25.5"
log = "0.4.22"
nalgebra = { version = "0.33.2", features = ["bytemuck"] }
pollster = "0.4.0"
wgpu = "23.0.0"
winit = "0.30.5"
